Repository Creaty-Co/creaty-web, pull requests merged in 2023-01, with the labels that each got.

#4 task-3
  .github/workflows/api-resulting-changes.yml
  .github/workflows/call-ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/main.yml
  .github/workflows/push-main.yml
Labels: devops

#2 Add new locales, Fix mentor page + tag indicators
  package-lock.json
  src/app/App.tsx
  src/app/components/other/ContactForm/ContactForm.tsx
  src/app/components/other/HaveQuestions/HaveQuestions.tsx
  src/app/components/popups/PopupAdmin/PopupAdminPersonalPage.scss
  src/app/components/popups/PopupAdmin/PopupAdminPersonalPage.tsx
  src/app/components/popups/PopupForm.tsx
  src/app/components/popups/PopupLayoutChanged.scss
  src/app/components/popups/PopupLayoutChanged.tsx
  src/app/views/admin/AdminMentorsView/AdminMentorsView.tsx
  src/app/views/home/HomeView.tsx
  src/app/views/user/User[userId].tsx
  src/i18n/locales/schema.json
  src/interfaces/types.ts
  src/redux/reducers/user.ts
Labels: task

#1 End Error Boundary
  src/app/components/services/ErrorBoundary.ts
  src/app/views/error/ErrorView.tsx
Labels: task

#18 fix: Change protocol for work on stage
  src/api/interceptors.ts
Labels: bug

#19 Fix protocol forget splash
  src/api/interceptors.ts
Labels: bug

#24 fix: Update dependencies
  @types/i18next/i18next.d.ts
  @types/react-i18next/index.d.ts
  @types/redux-thunk/redux-thunk.d.ts
  package-lock.json
  package.json
  src/app/App.tsx
  src/app/AppInit.ts
  src/app/components/admin/AdminEditableValue.tsx
  src/app/components/admin/AdminInterface.tsx
  src/app/components/admin/AdminTopbar.tsx
  src/app/components/other/ContactForm/ContactForm.tsx
  src/app/components/other/MentorSearch/MentorSearch.tsx
  src/app/components/popups/PopupAdmin/PopupAdminPersonalPage.tsx
  src/app/views/admin/AdminFormsView/AdminFormsView.tsx
  src/app/views/admin/AdminMentorView/AdminMentorNewEdit.tsx
  src/app/views/admin/AdminTopicsView/AdminTagsView.tsx
  src/app/views/admin/AdminTopicsView/AdminTopicsView.tsx
  src/app/views/home/DynamicPrimaryInfo/DynamicPrimaryInfo.tsx
  src/app/views/home/HelpfulCreaty/HelpfulCreaty.tsx
  src/app/views/home/HomeView.tsx
  src/app/views/home/HowItWorks/HowItWorks.tsx
  src/app/views/mentors/MentorsView[topicOrTag].tsx
  src/app/views/user/User[userId].tsx
  src/i18n/config.ts
  src/i18n/external-resource-backend.ts
  src/i18n/react-json-editor-thirdParty.tsx
Labels: task

#27 fix: Add i18next transform function
  src/app/views/home/HelpfulCreaty/HelpfulCreaty.tsx
Labels: bug
